---
title: "Initial Korean covid 19"
author: "Dorothy Decker"
date: "6/21/2023"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=2)
require(tidyverse)
require(tigerstats)
require(lubridate)
kRdata <- read.csv(file = 'kRdata.csv')
kRdata <- kRdata %>%
mutate(across(where(is.character), as.factor))

```
### Data is from the Patient_Info dataset from South Korea 1 Jan to 1 May 2020
### This data was retrieved from a downloadable zip file from kaggle

Some of the data was uncoded for sex - sex must be just male or female
77 of the data entries were coded sex  as blank, so we omit these.
state of a patient must be died or alive - we adjust that as well   
  
# Your Question - Is dying independent of sex?


## Methods

We will Investigate whether men and women are equally likely to die of COVID 19 from data collected in South Korea through May 2019. We will analyze the Sex of the patients and the result if they are alive or dead. The result is one of the variables. There is a factor variable $Sex and $sex with two levels, we have a helper file to use as a template to approach this problem. 




## Graphical results - use ggplot commands to do this  



  





  
## Numerical results


## Inferential results 




## Conclusions

